Denki PMDA minor cleanups
performancecopilot/pcp pull request #1575
Opened 2022-04-13 01:01 UTC by natoscott

2022-04-13 10:27 UTC, christianhorn requested changes
Can we remove line 246 and change 247 as follows?
  pmNotifyErr(LOG_DEBUG, "Assuming %s%s is a battery we should provide metrics for.",dirname,ep->d_name);
That will give us that one line of detail which directory is considered a battery, good to have that by default.

2022-04-13 10:35 UTC, christianhorn approved these changes

2022-04-13 10:37 UTC, christianhorn requested changes
Can we remove the conditional in line 664?
That would lead to one single announcement in log that (if) RAPL was found.

2022-04-13 22:49 UTC, natoscott commented
> Can we remove line 246 and change 247 as follows? pmNotifyErr(LOG_DEBUG, "Assuming %s%s is a battery we should provide metrics for.",dirname,ep->d_name); That will give us that one line of detail which directory is considered a battery, good to have that by default.

Will do (on both suggestions), thanks!  I'll also use LOG_INFO for these diagnostics rather than LOG_DEBUG.

2022-04-14 07:52 UTC, christianhorn approved these changes

2022-04-14 21:47 UTC, merged