Require python36-libvirt for all RHEL7 distros
performancecopilot/pcp pull request #1962
Opened 2024-04-20 05:58 UTC by Tualua

2024-04-21 23:38 UTC, natoscott commented on build/rpm/pcp.spec.in
> +%if 0%{?centos_ver}%{?rhel} == 7
@Tualua @kmcdonell can we remove centos_ver here then?  We don't use that rpm variable anywhere else, so it looks a little odd - and even more odd with this change :)

2024-04-24 04:53 UTC, natoscott requested changes
Can we drop 'centos_ver' here now?  (AIUI 'rhel' is a superset)

2025-02-12 17:40 UTC, kmcdonell commented on build/rpm/pcp.spec.in
> +%if 0%{?centos_ver}%{?rhel} == 7
I vote for replacing 0%{?centos_ver} by 0%{?rhel} here, which is not the same as the proposed patch.
But this really is a RH-folk decision, as "I know nothing".

2025-05-15 01:53 UTC, natoscott commented
Superceded by #2208 which (attempts to) answers my question.

2025-05-15 01:53 UTC, closed without merging